#!/bin/bash
# Simple reverse live check script
# Client : Call the script on server via ssh to save (arg -> hostname)
# Server : Call the script
# Server needs postfix/sendmail

TIMESTAMP_FILEPATH=$HOME/live-check-timestamps
TIME_DELAY="4 hour"
MESSAGE="Live-Check Expired"

function save(){
    mkdir -p $TIMESTAMP_FILEPATH
    date -d "$TIME_DELAY" +%s > "$TIMESTAMP_FILEPATH/$1"
    exit 0
}

function check(){
    if [ -d $TIMESTAMP_FILEPATH ]; then
        for file in $TIMESTAMP_FILEPATH/* ; do
            # Get basename from path
            filename="${file##*/}"
            if [ `date +%s` -ge `cat $file` ] ; then
                echo "$filename: $MESSAGE"
                # Only remove if mail sended correctly
                echo -e "Subject:$filename: $MESSAGE\n`date`" | sendmail $USER@`hostname` && rm $file
            fi
        done
    fi
    exit 0
}

if [ $# -eq 0 ]; then
    check
fi
if [ $# -eq 1 ] ; then
    save $1
fi
echo "Usage: live-check (arg > save | empty > check)"
