FROM nginx:mainline-alpine
ARG DOMAIN

VOLUME /etc/letsencrypt/
EXPOSE 80/TCP 443/TCP

RUN apk add certbot certbot-nginx bash

WORKDIR /root/
COPY docker-entrypoint.sh nginx.conf healthcheck.sh /root/
RUN find . -type f -print0 | xargs -0 sed -i 's/\[DOMAIN\]/'$DOMAIN'/g'
RUN chmod +x docker-entrypoint.sh
RUN chmod +x healthcheck.sh

HEALTHCHECK CMD ./healthcheck.sh

ENTRYPOINT ["/root/docker-entrypoint.sh"]
