#!/bin/bash

while ! ping -c 1 -W 1 1.1.1.1; do
    sleep 1
done
#because apparently waiting for network-online.target is not enough :(
/usr/local/bin/filebrowser --noauth -a {IP} -p 80 -r {dir with symblink}
