#!/bin/bash

while ! ping -c 1 -W 1 {test IP}; do
    sleep 1
done
#because apparently waiting for network-online.target is not enough :(
/usr/local/bin/filebrowser --noauth -a {IP} -p 3000 -r {dir with symblink} -d {filebrowser.db}
