#!/bin/bash
#TODO Description

TIMESTAMP_FILEPATH=$HOME/live-check-timestamps
TIME_DELAY="4 hour"
MESSAGE="Live-Check Expired"

function usage(){
    echo "Usage: live-check (arg > save | empty > check)"
    exit 1
}

function save(){
    mkdir -p $TIMESTAMP_FILEPATH
    date -d "$TIME_DELAY" +%s > "$TIMESTAMP_FILEPATH/$1"
    exit 0
}

function check(){
    if [ ! -d $TIMESTAMP_FILEPATH ]; then
        usage
        exit 1
    fi
    for file in $TIMESTAMP_FILEPATH/* ; do
        filename="${file##*/}"
        if [ `date +%s` -ge `cat $file` ] ; then
            echo "$filename: $MESSAGE"
            echo -e "Subject:$filename: $MESSAGE\n`date`" | sendmail $USER@`hostname` && rm $file
        fi
    done
    exit 0
}

if [ $# -eq 0 ]; then
    check
fi
if [ $# -eq 1 ] ; then
    save $1
fi
usage
