#!/bin/bash

#TODO Description
#TODO service emitter + receiver

TIMESTAMP_FILEPATH=$HOME/live-check-timestamp
TIME_DELAY=14400

function usage(){
    echo "Usage: live-check save/check"
    exit 1
}

function save(){
    date -d "$TIME_DELAY second" +%s > $TIMESTAMP_FILEPATH
    exit 0
}

function check(){
    while true
    do
        sleep $TIME_DELAY
        if [ -f "$TIMESTAMP_FILEPATH" ]; then
            timestamp=`cat $TIMESTAMP_FILEPATH`
            if [ `date +%s` -ge $timestamp ]; then
                echo "Live-check Expired"
                rm $TIMESTAMP_FILEPATH
                echo "Subject:Live-Check Expired" | sendmail $USER@$HOST
            fi
        fi
    done
}

if [ $# -eq 1 ]; then
    if [ $1 = "save" ]; then
        save
    fi
    if [ $1 = "check" ]; then
        check
    fi
fi
usage
