
[global]
	workgroup = WORKGROUP
	netbios name = MAGPIE
	guest account = username
	map to guest = bad user
	usershare allow guests = yes


[Angelique]
	path = /Angelique
	browseable = yes
	guest only = yes
	read only = no
	public = yes
	writable = yes
	printable = no
	force group = users
	force user = username
