#!/bin/bash

#TODO prise d'arg + ajout function

while true
do
    sudo cat /var/log/mail.log
    echo "If you want to completely stop the server process now, press Ctrl+C before
the time is up!"
    echo "Rebooting in: 60s"
    sleep 60
done

# Local Variables:
# mode: Shell-script
# coding: mule-utf-8
# End:
