FROM debian:latest
ARG DOMAIN

VOLUME /etc/letsencrypt/
VOLUME /post_base/
EXPOSE 25/TCP 587/TCP 465/TCP 143/TCP 993/TCP 80/TCP

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y --no-install-recommends postfix dovecot-core dovecot-imapd dovecot-lmtpd opendkim opendkim-tools syslog-ng

WORKDIR /root/
COPY config_files/ /root/
RUN /bin/bash -c 'chmod +x /root/*.sh'
RUN /root/confs_install.sh $DOMAIN

HEALTHCHECK --interval=5m --timeout=30s CMD ./Healthcheck.sh || exit 1

ENTRYPOINT ["/root/docker_entrypoint.sh"]
