FROM alpine:latest
ARG DOMAIN

VOLUME /etc/letsencrypt/
VOLUME /post_base/
EXPOSE 25/TCP 587/TCP 465/TCP 143/TCP 993/TCP 80/TCP

RUN apk add --update-cache postfix dovecot opendkim opendkim-utils syslog-ng procps bash

WORKDIR /root/
COPY config_files/ /root/
RUN /bin/bash -c 'chmod +x /root/*.sh'
RUN /root/confs_install.sh $DOMAIN

# Fix syslog error
RUN /bin/bash -c 'echo "SYSLOGNG_OPTS=\"--no-caps\"" >> /etc/default/syslog-ng'

HEALTHCHECK CMD ./healthcheck.sh

ENTRYPOINT ["/root/docker_entrypoint.sh"]
