#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "One parameter needed"
    exit 1
fi


notify-send "App Launcher" "$1 started" -r 220 -u low
$1 || notify-send "App Laucher" "$1 failed" -u critical -r 220 -t 1000
