#!/bin/bash
if [ "$#" -ge 2 ]; then
    echo "USAGE: script \"device_name\""
    exit 1
fi
# Lockfile sample (block multiple instances)
LOCKFILE="/var/run/user/$UID/$(basename "$0").lock"
[ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"

safe_exit() {
    echo "$1"
    rm "$LOCKFILE"
    exit "$2"
}

main() {
    TIME_DELAY="5 minutes" # Time delay sample (if exceeded time -> timeout)
    if [ "$#" -eq 1 ]; then
        DEVICE_NAME=$1
    else
        echo "No bluetooth device given, using first registered device on bluetoothctl"
        DEVICE_NAME=`bluetoothctl devices | head -n 1 | cut -d " " -f 3-10`
    fi

    systemctl status bluetooth.service | grep "^\s*Status: \"Running\"$" 1>/dev/null || sudo systemctl start bluetooth 1>/dev/null
    bluetoothctl power on 1>/dev/null
    DEVICE_MAC=$(bluetoothctl devices | grep -oP "(?<=\s)..:..:..:..:..:..(?=\s*$DEVICE_NAME\$)") || safe_exit "\"$DEVICE_NAME\" not paired" 1
    while [ "$(date +%s)" -lt "$(date -d "$TIME_DELAY" +%s)" ]; do
        if bluetoothctl connect "$DEVICE_MAC" 1>/dev/null; then
            # Fix -> remove set-card-profile switch and check if unneeded
            sleep 5
            pactl set-card-profile $(pactl list short | grep bluez_card | cut -f 1) a2dp-sink-aac
            if pactl set-card-profile $(pactl list short | grep bluez_card | cut -f 1) a2dp-sink; then
                safe_exit "\"$DEVICE_NAME\" connected" 0
            fi
        else
            sleep 1
        fi
    done
    safe_exit "\"$DEVICE_NAME\" connect timeout" 1
}

main "$1"
