#!/bin/bash
if [ "$#" -ge 2 ]; then
    echo "USAGE: script \"device_name\""
    exit 1
fi
# Lockfile sample (block multiple instances)
LOCKFILE="/var/run/user/$UID/$(basename "$0").lock"
[ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"

safe_exit() {
    echo "$1"
    rm "$LOCKFILE"
    exit "$2"
}

main() {
    TIMEOUT_DELAY="1 minute"
    TIMEOUT="$(date -d "$TIMEOUT_DELAY" +%s)"
    if [ "$#" -eq 1 ]; then
        DEVICE_NAME=$1
        DEVICE_MAC=$(bluetoothctl devices | grep -oP "(?<=\s)..:..:..:..:..:..(?=\s*$DEVICE_NAME\$)") || safe_exit "\"$DEVICE_NAME\" not paired" 1
    else
        if bluetoothctl devices | grep -i device &>/dev/null; then
            echo "No bluetooth device given, using first registered device on bluetoothctl"
            DEVICE_MAC=`bluetoothctl devices | head -n 1 | cut -d " " -f 2`
            DEVICE_NAME=`bluetoothctl devices | head -n 1 | cut -d " " -f 3-10`
        else
            safe_exit "Please register a device with bluetoothctl or give device_name as argument" 1
        fi
    fi

    bluetoothctl power on 1>/dev/null
    while [ "$(date +%s)" -lt "$TIMEOUT" ]; do
        if bluetoothctl connect "$DEVICE_MAC" 1>/dev/null; then
            if ! pactl set-card-profile $(pactl list short | grep bluez_card | cut -f 1) a2dp-sink; then
                sleep 4
                pactl set-card-profile $(pactl list short | grep bluez_card | cut -f 1) a2dp-sink-aac
            fi
            if pactl set-card-profile $(pactl list short | grep bluez_card | cut -f 1) a2dp-sink; then
                notify-send "Bluetooth" "$DEVICE_NAME connected" -i audio-headset
                safe_exit "\"$DEVICE_NAME\" connected" 0
            fi
        else
            sleep 1
        fi
    done
    notify-send "Bluetooth" "$DEVICE_NAME timeout" -u critical -i audio-headset
    safe_exit "\"$DEVICE_NAME\" connect timeout" 1
}

main $*
