#!/bin/bash

ALL=$@
if [[ $1 == "start" ]]; then
    dir="$XDG_RUNTIME_DIR/cliphist"
    mkdir -p $dir
    LOCKFILE="$dir/$(basename "$0").lock"
    [ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"
    trap "rm -f $LOCKFILE && exit 0" EXIT INT TERM
    ln -sf $XDG_RUNTIME_DIR/cliphist $HOME/.cache/
    wl-paste --watch cliphist store
elif [[ $1 == "decode" ]]; then
    cliphist $@
else
    cliphist $@ -db-path="$XDG_RUNTIME_DIR/cliphist/db"
fi
