#!/bin/bash
LOCKFILE="$XDG_RUNTIME_DIR/$(basename "$0").lock"
[ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"
trap "rm -f $LOCKFILE && exit 0" EXIT INT TERM

while ! ping 1.1.1.1 -c 1 &>/dev/null
do
    sleep 5s
done
sleep 5m
while :
do
    sudo pacman -Syq &>/dev/null
    pacman -Quq 2>/dev/null > $XDG_RUNTIME_DIR/pacman-update-list
    sleep 1h
done
