#!/bin/bash

# Lockfile sample (block multiple instances)
LOCKFILE="/var/run/user/$UID/$(basename "$0").lock"
LOGFILE="/var/run/user/$UID/iostat.log"
[ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"
trap "rm -f $LOGFILE $LOCKFILE && exit 0" EXIT INT TERM

while swaymsg; do iostat -dhxy 2 300 > $LOGFILE; sleep 0.1; done

