#!/bin/bash
ID=100
DESC="Sway Cheat Sheet"
TIMEOUT_DELAY="15 minutes"
TIMEOUT="$(date -d "$TIMEOUT_DELAY" +%s)"
notify-send -t 3600000 -r $ID "$DESC" "Super + Enter: Terminal\nSuper + G: Internet browser\nSuper + n: File browser"

echo "Starting $DESC"
while ( ! pgrep firefox 1>/dev/null ) && ( ! pgrep tofi-run 1>/dev/null ) && ( ! pgrep thunar 1>/dev/null ) && [ "$(date +%s)" -lt "$TIMEOUT" ] ; do
    sleep 0.1
done
echo "Closing $DESC"
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.CloseNotification $ID 1>/dev/null
