#!/bin/bash

dir="/run/user/$(id -u)/sway-screenshot"
title="Sway Screenshot"

if [ "$1" == "picture" ] ; then
    if GEO="$(slurp)" ; then
        grim -g "$GEO" - | wl-copy
        mkdir -p $dir
        file="$dir/picture-`date +"%s"`"
        wl-paste > $file
        notify-send "$title" "Picture copied to the clipboard\nand to $file" -t 8000
        exit 0
    fi
elif [ "$1" == "video" ] ; then
    #TODO add sound
    if pgrep "wf-recorder" &>/dev/null ; then
        killall "wf-recorder"
        notify-send "Screenshot" "Video copied to $(cat $dir/last_video)" -t 8000
        exit 0
    fi
    if GEO="$(slurp)" ; then
        mkdir -p $dir
        file="$dir/video-`date +"%s"`.mkv"
        echo $file > $dir/last_video
        notify-send "$title" "Video recording started\nrestart to stop" -t 8000
        wf-recorder -g "$GEO" --file=$file || notify-send "Screenshot" "Video recording failed" -t 8000 -u critical
        exit 0
    fi
fi

notify-send "$title" "Screenshot failed" -t 8000 -u critical
echo "Usage: ./script picture||video"
