#!/bin/bash
ID=100
DESC="Sway Cheat Sheet"
TIMEOUT_DELAY="15 minutes"
TIMEOUT="$(date -d "$TIMEOUT_DELAY" +%s)"
CHEATSHEET=$(cat <<-END
Super + ?: Display this Cheat Sheet
Super + Enter: Terminal
Super + d: Application launcher

Super + g: Internet browser
Super + n: File browser
Super + Shift + m: Monitor rotation
Super + b: Connect Bluetooth

Super + p + Escape: Power off
Super + s + Escape: Suspend
Super + r + Escape: Reboot
Super + Shift + r + Escape: Force reboot
END
)

echo "Starting $DESC"
echo $1
if [ "$1" == "info" ]; then
    LOCKFILE="/var/run/user/$(id -u)/sway-tuto.lock"
    if [ -f "$LOCKFILE" ]; then
        gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.CloseNotification $ID 1>/dev/null
        rm "$LOCKFILE"
    else
        notify-send -t 3600000 -r $ID "$DESC" "$CHEATSHEET" && touch "$LOCKFILE"
    fi
else
    notify-send -t 3600000 -r $ID "$DESC" "$CHEATSHEET"
    while ( ! pgrep firefox 1>/dev/null ) && ( ! pgrep tofi-run 1>/dev/null ) && ( ! pgrep thunar 1>/dev/null ) && ( ! pgrep alacritty 1>/dev/null ) && [ "$(date +%s)" -lt "$TIMEOUT" ] ; do
        sleep 0.1
    done
    gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.CloseNotification $ID 1>/dev/null
fi
echo "Closing $DESC"
