#!/bin/bash
ID=100
DESC="Sway Cheat Sheet"
TIMEOUT_DELAY="15 minutes"
CHEATSHEET=$(cat <<-END
Option: 󰨡 or 󰘵
Option + ?: Display this Cheat Sheet
Option + Enter: Terminal
Option + d: Application launcher

Option + g: Internet browser
Option + t: File browser
Option + Shift + m: Monitor 90° rotation
Option + b: Connect Bluetooth

Print Screen: Image screenshot
Option + Print Screen: Video screenshot
Pause: Copy history list
Option + Pause: Reset copy history

Option + F1/F2/F3/F4/F5: Mpd Toggle/Prev/Next/Stop/Mute

Option + 1-10: Focus to workspace 1-10
Option + Shift + 1-10: Move window to workspace 1-10
Option + Ctrl + left/right: Move to left/right workspace

Option + Arrow: Change focused window
Option + Shift + Arrow: Move window
Option + h/v: Split horizontaly/verticaly
Option + f: Full screen focused window
Option + s/z/e: Change container layout to stacked/tabbed/toggle split
Option + Shift + Space: Toggle floating window
Option + Space: Toggle focus between tiling and floating
Option + p/c: Focus parent/child window
Option + r: Resize window
Option + Shift + a: Kill focused window
Option + \`: Swap container to one on the next displayed monitor

Option + Shift + r: Reload sway
Ctrl + Escape + p: Power off
Ctrl + Escape + s: Suspend
Ctrl + Escape + r: Soft reboot
Ctrl + Escape + Shift: Hard reboot
END
)

echo "Starting $DESC"
if [ "$1" == "info" ]; then
    LOCKFILE="$XDG_RUNTIME_DIR/sway-tuto.lock"
    if [ -f "$LOCKFILE" ]; then
        gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.CloseNotification $ID 1>/dev/null
        rm "$LOCKFILE"
    else
        notify-send -u low -t 3600000 -r $ID "$DESC" "$CHEATSHEET" && touch "$LOCKFILE"
    fi
else
    sleep 4
    notify-send -t 3600000 -u low -r $ID "$DESC" "$CHEATSHEET"
    while ( ! pgrep "firefox|rofi|thunar|alacritty" -l && pgrep sway -x --quiet ) ; do
        sleep 0.1
    done
    gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.CloseNotification $ID 1>/dev/null
fi
echo "Closing $DESC"
