#!/bin/bash
RUN_FILE_PATH="/run/user/`id -u`/waybar"
mkdir -p $RUN_FILE_PATH
TIMESTAMP_FILE_PATH="$RUN_FILE_PATH/waybar-aur-time"
COUNT_FILE_PATH="$RUN_FILE_PATH/waybar-aur-count"
PIKAUR_DELAY=1800 #30min
if [ ! -f $TIMESTAMP_FILE_PATH ] || [ "$(( `date +%s` - `cat $TIMESTAMP_FILE_PATH`))" -gt "$PIKAUR_DELAY" ] ; then
    sudo pikaur -Syq &>/dev/null && date +%s > $TIMESTAMP_FILE_PATH
fi
pk_count=`sudo pikaur -Quq 2>/dev/null | wc -l`
if [ "$pk_count" -gt 0 ] ; then
    if [ ! -f $COUNT_FILE_PATH ] || [ "$(( `cat $COUNT_FILE_PATH`))" -ne "$pk_count" ] ; then
        notify-send -t 15000 -r 40 "Pikaur update available" "$pk_count packages to update"
    fi
    echo "<span font='12' color=\"#b36807\"> </span>$pk_count"
fi
echo $pk_count > $COUNT_FILE_PATH
# 3 icons : fail noupdate/empty updates (count ?)
# interval every 5min
