#!/bin/bash

#device=`pactl list sinks | grep -Pzo "$(pactl get-default-sink)(.|\n)*api.bluez5.address.*\"\K.*(?=\")" | tr '\0' '\n'`
#percentage=`bluetoothctl info $device | grep -oP "Battery Percentage.*\(\K\d+(?=\))"`
device=$(upower -e | grep "$1")
percentage=`upower -i "$device" | grep -oP "percentage:\D*\K\d+(?=%)(?!.*,)"`

if echo $1 | grep "ps_controller" &>/dev/null; then
    model="<span font='14' color='#2e6db4'>󰐔</span>"
elif echo $1 | grep "headset" &>/dev/null; then
    model=
else
    model=""
fi

if upower -i "$device" | grep -oP "battery\S*?symbolic" | grep "charging" &>/dev/null; then
    is_charging=󱐋
else
    is_charging=""
fi

#tooltip=`pactl list sinks | grep -Pzo "$(pactl get-default-sink)(.|\n)*media\.name.*\"\K.*(?=\")" | tr '\0' '\n'`
tooltip=`upower -i $device | grep -oP "serial:\s*\K.*$" | tr '\0' '\n'`

if [ -z "${device}" ] || [ -z "${percentage}" ] ; then
    echo "{\"text\": \"\", \"tooltip\": \"\"}"
    exit 0
fi

if [ $percentage -ge 70 ]; then
    text="<span font='14' color='#28b463'>$model 󱊣$is_charging </span><span>$percentage%</span>"
elif  [ $percentage -ge 35 ]; then
    text="<span font='14' color='#28b463'>$model 󱊢$is_charging </span><span>$percentage%</span>"
elif  [ $percentage -ge 10 ]; then
    text="<span font='14' color='#FFA500'>$model 󱊡$is_charging </span><span>$percentage%</span>"
elif  [ $percentage -lt 10 ]; then
    text="<span font='14' color='#FF0000'>$model 󰂎$is_charging </span><span>$percentage%</span>"
fi


echo "{\"text\": \"$text\", \"tooltip\": \"$tooltip\"}"
# {"text": "$text", "alt": "$alt", "tooltip": "$tooltip", "class": "$class", "percentage": $percentage }
