#! /bin/bash

bar="▁▂▃▄▅▆▇█"
dict="s/;//g;"

# creating "dictionary" to replace char with bar
i=0
while [ $i -lt ${#bar} ]
do
    dict="${dict}s/$i/${bar:$i:1}/g;"
    i=$((i=i+1))
done

# write cava config
config_file="/run/user/`id -u`/waybar/polybar_cava_config"
echo "
[general]
bars = 60

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
" > $config_file

# read stdout from cava
cava -p $config_file | while read -r line; do
if [ "`mpc | wc -l`" -eq 1 ]; then
    echo ""
else
    line=`sed $dict <<< "$line"`
    song=`mpc current | sed -e 's/\&/&amp;/'`
    if mpc | grep "paused" &>/dev/null ; then
        status="<span font='14' color=\"#28b463\">󰏤</span>"
        line="$status $song"
        echo $line
    else
        status="<span font='14' color=\"#28b463\">󰐊</span>"
        line="${line:0:30} $status $song ${line:30}"
        echo $line
    fi
fi
done
