#!/bin/bash -
#TODO add enum icons + max via sensors

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit
fi

if [ "$1" == "amd" ]; then
    sensors amdgpu-pci-0b00 -u | grep -oP 'temp1_input:\ *\K\d+'
elif [ "$1" == "nvidia" ]; then
    nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader
fi
