#!/bin/bash
IOFILE=/run/user/`id -u`/iostat.log
if [ -f $IOFILE ]; then
    iolist=$(grep -oP '\S{,4}% \S*$' $IOFILE | sort -k1,1)
    iotop=`printf %s "$iolist" | tail -n 1`
    iolist=$(echo $iolist)
end=""
b=0
for (( i=0; i<${#iolist}; i++ )); do
    char="${iolist:$i:1}"
    if [ "$char" == " " ]; then
        if [ $b = 0 ]; then
            b=1
        end=$end$char
    else
        b=0
    end=$end"\r"
        fi
    else
    end=$end$char
    fi
done
text="<span font='14' color='#FF4D00'>󱛟 </span><span>$iotop</span>"
fi
echo {\"text\": \""$text"\", \"tooltip\": \""$end"\"}
# {"text": "$text", "alt": "$alt", "tooltip": "$tooltip", "class": "$class", "percentage": $percentage }
