#!/bin/bash

# TODO colors warning error (raw or css ?)
statfull=$(cat /proc/pressure/io| grep 'full')
stat=$(echo $statfull | grep -oP '.*avg10=\K\d*(?=\.?\d* avg60)')
if [ ${#stat} -eq 1 ] ; then
    stat=' '$stat
fi
text="<span font='14' color='#75542e'>󰞰 </span>$stat%"
echo "{\"text\": \"$text\", \"tooltip\": \"$statfull\"}"
