#!/bin/bash

mkdir -p $XDG_RUNTIME_DIR/waybar
LOCKFILE="$XDG_RUNTIME_DIR/waybar/$(basename "$0").lock"
CONFIG_FILE="$XDG_RUNTIME_DIR/waybar/waybar-cava-config"
[ -f "$LOCKFILE" ] && ps -p "$(cat "$LOCKFILE")" >/dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ >"$LOCKFILE"
trap "rm -f $LOCKFILE && exit 0" EXIT INT TERM

bar="▁▂▃▄▅▆▇█"
dict="s/;//g;"

# creating "dictionary" to replace char with bar
i=0
while [ $i -lt ${#bar} ]
do
    dict="${dict}s/$i/${bar:$i:1}/g;"
    i=$((i=i+1))
done

if ! [ -f "$CONFIG_FILE" ]; then
    # write cava config
    echo "
    [general]
    bars = 60

    [output]
    method = raw
    raw_target = /dev/stdout
    data_format = ascii
    ascii_max_range = 7
    " > $CONFIG_FILE
fi

mpc_text=`mpc`

if echo $mpc_text | grep "paused" &>/dev/null ; then
    song=`echo $mpc_text | grep -oP "^.*(?=\[)" | sed -e 's/\&/&amp;/g'`
    status="<span font='14' color='#28b463'>󰏤</span>"
    echo $status $song
    # cava should only run if a song is playing
elif echo $mpc_text | grep "playing" &>/dev/null ; then
    # read stdout from cava
    cava -p $CONFIG_FILE | while read -r line; do
    mpc_text=`mpc`
    if echo $mpc_text | grep "playing" &>/dev/null ; then
        line=`sed $dict <<< "$line"`
        song=`echo $mpc_text | grep -oP "^.*(?=\[)" | sed -e 's/\&/&amp;/g'`
        progress="$((60*($(echo $mpc_text | grep -oP "\(\K\d*"))/100))"
        status="<span font='14' color='#28b463'>󰐊</span>"
        if [[ "$progress" -lt 30 ]]; then
            echo "<span color='#28b463'>${line:0:$progress}</span>${line:$progress:30-$progress} $status $song ${line:30}"
        else
            echo "<span color='#28b463'>${line:0:30}</span> $status $song <span color='#28b463'>${line:30:$progress-30}</span>${line:$progress}"
        fi
    else
        kill $(pgrep -f "cava -p $CONFIG_FILE") 2>/dev/null
    fi
done
else
    echo ""
fi
