#!/bin/bash
COUNT_FILE_PATH=$XDG_RUNTIME_DIR/waybar/pacman-update-count
UPDATE_LIST=`pacman -Qu`
if [[ -n "$UPDATE_LIST" ]]; then
    COUNT=`echo "$UPDATE_LIST" | wc -l`
    if [ "$COUNT" -gt 0 ] ; then
        mkdir -p $XDG_RUNTIME_DIR/waybar
        if [ ! -f $COUNT_FILE_PATH ] || [ "$(( `cat $COUNT_FILE_PATH`))" -ne "$COUNT" ] ; then
            notify-send -t 15000 -r 40 "$COUNT packages to update" "$(head -n 30 <<< $UPDATE_LIST)"
            echo "$COUNT" > "$COUNT_FILE_PATH"
        fi
        text="<span font='14' color='#994F00'>󱍸 </span>$COUNT"
        tooltip="Updates available:\r${UPDATE_LIST//$'\n'/'\r'}"
        echo "{\"text\": \"$text\", \"tooltip\": \"$tooltip\"}"
        exit 0
    fi
else
    rm -f $COUNT_FILE_PATH
fi
echo "{\"text\": \"\", \"tooltip\": \"\"}"

# {"text": "$text", "alt": "$alt", "tooltip": "$tooltip", "class": "$class", "percentage": $percentage }
