#!/bin/bash

status=$(ls /sys/class/net/*wg* &>/dev/null || ls /sys/class/net/*tun* &>/dev/null ; echo $?)
ip=""

if [ "$status" == 0 ]; then
    if mullvad -V &>/dev/null && mullvad status 2>/dev/null | grep Connected &>/dev/null; then
        pre_ip=$(mullvad status | grep -oP "IPv\d:\s*\K\S*$")
        if [[ ! -z "$pre_ip" ]]; then
            ip=" <span color='#FFFFFF'>$pre_ip</span>"
        fi
    fi
    echo "󰌾$ip"
else
    echo ''
fi
