FROM jlesage/jdownloader-2
RUN apk add curl

COPY reco.sh /root/
RUN chmod +x reco.sh
HEALTHCHECK --interval=5m CMD  curl -f -s http://localhost:5800 1>/dev/null && ping -c 1 1.1.1.1 1>/dev/null || exit 1 