#!/bin/bash

# lockfile sample (block multiple instances)
lockfile="/var/run/user/$UID/$(basename "$0").lock"
[ -f "$lockfile" ] && ps -p $(cat $lockfile) > /dev/null && echo "$(basename "$0") is already running." && exit 1 || echo $$ > $lockfile

# Time delay sample (if exceeded time -> timeout)
TIME_DELAY=`date -d "5 minutes" +%s`

bluetoothctl power on 1>/dev/null
while [ `date +%s` -lt $TIME_DELAY ]
do
    bluetoothctl connect E4:22:A5:BE:4E:E5 1>/dev/null
    if [[ $? == 0 ]]; then
        echo "PLT connected"
        rm $lockfile
        exit 0
    fi
    sleep 1
done
echo "PLT connect timeout"
rm $lockfile
exit 1
