export MPD_HOST="$HOME/.config/mpd/mpd_socket"

if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
    export QT_QPA_PLATFORM=wayland
    export _JAVA_AWT_WM_NONREPARENTING=1
    export MOZ_ENABLE_WAYLAND=1
    exec sway 1>/tmp/sway.log 2>/var/tmp/sway_err.log
fi
