FROM debian:latest
ARG DOMAIN

VOLUME /etc/letsencrypt/
VOLUME /var/log/
EXPOSE 80/TCP 443/TCP

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y --no-install-recommends syslog-ng nginx certbot python3-certbot-nginx cron

RUN certbot --nginx --keep --quiet --register-unsafely-without-email --agree-tos  -d $DOMAIN -d vw.$DOMAIN -d www.$DOMAIN &>/var/log/certbot.log

WORKDIR /etc/nginx
COPY nginx.conf .
RUN find . -type f -print0 | xargs -0 sed -i 's/\[DOMAIN\]/'$DOMAIN'/g'


WORKDIR /root/
COPY docker-entrypoint.sh .
RUN /bin/bash -c "chmod +x docker-entrypoint.sh"
ENTRYPOINT ["/root/docker-entrypoint.sh"]
