FROM debian:latest
ARG DOMAIN

VOLUME /etc/letsencrypt/

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y --no-install-recommends nginx certbot python3-certbot-nginx

WORKDIR /root/
COPY config_files/ /root/
RUN /bin/bash -c 'chmod +x /root/*.sh'
RUN /root/confs_install.sh $DOMAIN

ENTRYPOINT ["/root/docker_entrypoint.sh"]
