name: CI

on:
  push:
  pull_request:

jobs:
  check:
    name: Run docker tester for install.sh
    container:
      image: ubuntu:latest
      volumes:
        - /docker-data-nobackup/install-test-logs:/docker-data-nobackup/install-test-logs

    steps:
      - name: Étape Préparatoire - Installation des outils de test
        run: |
          apt-get update && apt-get install -y git docker.io docker-buildx

      - name: Étape 1 - Public Git Clone
        run: |
          git clone ${{ gitea.server_url }}/${{ gitea.repository }}.git .
          git checkout ${{ gitea.sha }}

      - name: Étape 2 - Run tester
        run: docker_conf/install_test/docker-run.sh
