#!/bin/bash

OVPN_DATA="/docker-data/openvpn"
#Careful with host
docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://"$(hostnamectl hostname)"
docker run -v $OVPN_DATA:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
