#!/usr/bin/env python3

# This is a script that checkes the gmail unread count.

from urllib.request import urlopen, URLError, FancyURLopener



try:
    urlopen("http://www.google.com")
except URLError as e:
    try:
        lines = open("/home/exo/.i3/unread.log").read().split('\n')
        print(lines[0])
        print(lines[0])
    except IOError:
        print(" Miss Unread")
        print(" N")
        print("#FF0000")
    else:
        print("#FF0000")
else:
    try:
        lines = open('/home/exo/.i3/gmail.log').read().split('\n')
    except IOError:
        print(" Miss id")
        print(" N")
        
    username = lines[0]
    password = lines[1]
    url = 'https://%s:%s@mail.google.com/mail/feed/atom' % (username, password)

    opener = FancyURLopener()
    page = opener.open(url)

    contents = page.read().decode('utf-8')


    ifrom = contents.index('<fullcount>') + 11
    ito   = contents.index('</fullcount>')

    unread = contents[ifrom:ito]

    try:
        fh = open("/home/exo/.i3/unread.log", "w")
        fh.write(unread)
    except IOError:
        print("Error")
    else:
        fh.close()
        
        if unread != "0":
            print(" "+unread)
            print(" "+unread)
            print("#0066cc")
        else:
            print(" 0")
            print(" 0")
            print("#0FF00")
