#!/usr/bin/perl

use strict;
use warnings;
use utf8;

open (iw2, "(iwgetid -r) |") or die;
# $iw='(iwgetid -r)'
my $iw=<iw2>;
close(iw2);
if ($iw eq ""){
    print "WifiDown\n";
    print "WifiDown\n";
    print "#FF0000\n";
}
else
{
    print $iw;
    print $iw;
}

exit 0;
