#!/bin/bash

FORMAT="%H:%M"
INSTANCE="${BLOCK_INSTANCE}"


if [ -z ${INSTANCE} ]
then
    DATETIME=$(date "+${FORMAT}")
else
    DATETIME=$(TZ="${INSTANCE}" date "+${FORMAT}" )
fi


   
echo "${DATETIME}"
echo "${DATETIME}"
echo ""
