#!/bin/bash

INSTANCE="${BLOCK_INSTANCE:-1}"

load=$(cat /proc/loadavg | awk -F ' ' '{print $'"${INSTANCE}"'}')

cpus="$(nproc)"

# full text
echo "$load"

# short text
echo "$load"

# color if load is too high
awk -v cpus=$cpus -v cpuload=$load '
    BEGIN {
        if (cpus <= cpuload) {
            print "#FF0000";
            # exit 33;
        }
    }
'
