#!/bin/bash

interval=2
min_volume=0
max_volume=100
volume=`pactl get-sink-volume @DEFAULT_SINK@ | grep -oP '\d+(?=%)(?!.*,)'`

if [ "$1" == "UP" ]
then
    volume=$(( $volume + $interval ))
    volume=$(( $volume > $max_volume ? $max_volume : $volume ))
    pactl set-sink-volume @DEFAULT_SINK@ $volume%
    notify-send -t 500 "Volume: $volume%"
elif [ "$1" == "DOWN" ]
then
    volume=$(( $volume - $interval ))
    volume=$(( $volume < $min_volume ? $min_volume : $volume ))
    pactl set-sink-volume @DEFAULT_SINK@ $volume%
    notify-send -t 500 "Volume: $volume%"
elif [ "$1" == "MUTE"  ]
then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    notify-send -t 1000 "$(pactl get-sink-mute @DEFAULT_SINK@)"
else
    echo "Usage: ./script UP|DOWN|MUTE"
fi
