#!/bin/bash

interval=1
min_volume=0
max_volume=100
volume=`pactl get-sink-volume @DEFAULT_SINK@ | grep -i Volume | cut -d '/' -f 2 | tr -d -c 0-9`

if [ "$1" == "UP" ]
then
    volume=$(( $volume + $interval ))
    volume=$(( $volume >= $max_volume ? $max_volume : $volume ))
    pactl set-sink-volume @DEFAULT_SINK@ $volume%
elif [ "$1" == "DOWN" ]
then
    volume=$(( $volume - $interval ))
    volume=$(( $volume <= $min_volume ? $min_volume : $volume ))
    pactl set-sink-volume @DEFAULT_SINK@ $volume%
elif [ "$1" == "MUTE"  ]
then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
else
    echo "Usage: ./script UP|DOWN|MUTE"
fi
