ARG IMG
FROM $IMG

WORKDIR /root/
RUN mkdir -p /root/logs/
COPY install.sh /root/install.sh
COPY test-engine.sh /root/test-engine.sh
RUN find . -type f -print0 | xargs -0 sed -i 's/\[IMG\]/'"$img"'/g'
RUN chmod +x install.sh test-engine.sh

ENTRYPOINT ["/root/test-engine.sh"]