#!/bin/bash -
acpi=`acpi`
status=`echo $acpi | gawk '{ print $3 }'`
if [ `echo $status` == 'Discharging,' ]; then
    remaining=`echo $acpi | gawk '{ print $5 }'`
    echo %{u#ff8000}%{+u}$remaining
else
    echo
fi
