#!/bin/bash -

temp=`sensors amdgpu-pci-0b00 -u | grep temp2_input | cut -b 16-17`
max_temp=80
if [ ${#temp} -gt 10 ]; then
    echo "%{u#00ff00}%{+u}%{F#00ff00}﨎 %{F-}Error nvidia-smi"
    exit
fi
display="%{u#00ff00}%{+u}%{F#00ff00}﨎 %{F-}"$temp"°C"
alert_display="%{u#00ff00}%{+u}%{F#00ff00}﨎 %{F-}%{F#f00}"$temp"°C%{F-}"
if [ $temp -gt $max_temp ]; then
    echo $alert_display
else
    echo $display
fi
