#!/bin/bash -

temp=`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`
max_temp=80
display="%{u#00ff00}%{+u}%{F#00ff00}﨎 %{F-}"$temp"°C"
alert_display="%{u#00ff00}%{+u}%{F#00ff00}﨎 %{F-}%{F#f00}"$temp"°C%{F-}"
if [ $temp -gt $max_temp ]; then
    echo $alert_display
else
    echo $display
fi
