#!/bin/sh

temp=`nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader`
max_temp=80
display="%{F#5a5a5a} %{F-}"$temp"°C"
if [ $temp -gt $max_temp ]; then
    echo %{u#ff0000}%{+u}$display
else
    echo %{u#00ff00}%{+u}$display
fi
exit 0
