#!/bin/bash
# Simple live check script
#
# Set timestamps -> 2 ways:
#
# 1 : Client use '/usr/bin/bash -c "ssh SERVER /usr/bin/live-check %H"'
# 2 : Server use '/usr/bin/bash -c "ping -c 2 CLIENT && /usr/bin/live-check CLIENT || :"'
#
# Check timestamps:
# Server : /usr/bin/live-check
# Use with systemd -> requires online + error to mail + timer

TIMESTAMP_FILEPATH=/docker-data/live-check-timestamps
MESSAGE="Live-Check Expired"
TIME_DELAY="30 minute"

function save(){
    mkdir -p $TIMESTAMP_FILEPATH
    date +%s > "$TIMESTAMP_FILEPATH/$1"
    exit 0
}

function check(){
    #TODO must change html -> status page
    if [ -d $TIMESTAMP_FILEPATH ]; then
        for file in $TIMESTAMP_FILEPATH/* ; do
            # Get basename from path
            filename="${file##*/}"
            file_timestamp=`cat $file`
            if [ `date -d "-$TIME_DELAY" +%s` -ge "$file_timestamp" ] ; then
                echo "$filename: $MESSAGE"
                # Only remove if mail sended correctly
                echo -e "Subject:$filename: $MESSAGE\n`date`" | sendmail $USER@`hostname` && rm $file
            fi
        done
    fi
    exit 0
}

if [ $# -eq 0 ]; then
    check
fi
if [ $# -eq 1 ] ; then
    save $1
fi
echo "Usage: live-check (arg > save | empty > check)"
