#!/bin/bash
# Dumb raspberry wifi fix
# After online detected, if no online for 1h -> reboot

while ! ping -c 1 1.1.1.1 1>/dev/null; do
    sleep 5m
done

echo "Internet detected, starting Net-Lifeguard"

while true
do
    sleep 30m
    ping -c 1 1.1.1.1 1>/dev/null
    if [[ $? -ne 0 ]]; then
        sleep 30m
        ping -c 1 1.1.1.1
        if [[ $? -ne 0 ]]; then
            echo "Internet connexion lost, restarting..."
            systemctl reboot
        fi
    fi
done
