FROM alpine:latest

RUN apk add --update-cache python3 py3-pip rsync git ffmpeg
RUN pip3 install mutagen
RUN pip3 install "git+https://github.com/ytdl-org/youtube-dl.git"

WORKDIR /root/
COPY docker-entrypoint.sh ydl /root/
RUN chmod +x docker-entrypoint.sh ydl
ENTRYPOINT ["/root/docker-entrypoint.sh"]
