#!/bin/bash
# PostUp = /usr/bin/bash -c 'exec /usr/bin/vpn_iptables_switch up %i'
# PreDown = /usr/bin/bash -c 'exec /usr/bin/vpn_iptables_switch down %i'
if [ "$#" -ne 2 ]; then
    echo "$1: usage : script up/down interface"
    exit 3
fi
if [ "$1" == "up" ]; then
    iptables -I OUTPUT ! -o $2 -m mark ! --mark $(wg show $2 fwmark) -m addrtype ! --dst-type LOCAL -m owner --uid-owner vpn_user -j REJECT
    ip6tables -I OUTPUT ! -o $2 -m mark ! --mark $(wg show $2 fwmark) -m addrtype ! --dst-type LOCAL -m owner --uid-owner vpn_user -j REJECT
    iptables -D OUTPUT -m owner --uid-owner vpn_user -j REJECT
    ip6tables -D OUTPUT -m owner --uid-owner vpn_user -j REJECT
elif [ "$1" == "down" ]; then
    iptables -I OUTPUT -m owner --uid-owner vpn_user -j REJECT
    ip6tables -I OUTPUT -m owner --uid-owner vpn_user -j REJECT
    iptables -D OUTPUT ! -o $2 -m mark ! --mark $(wg show $2 fwmark) -m addrtype ! --dst-type LOCAL -m owner --uid-owner vpn_user -j REJECT
    ip6tables -D OUTPUT ! -o $2 -m mark ! --mark $(wg show $2 fwmark) -m addrtype ! --dst-type LOCAL -m owner --uid-owner vpn_user -j REJECT
else
    echo "$1: usage : script up/down interface"
    exit 3
fi