#!/bin/bash
# USAGE $1=Host $2=output_dir
HOST=$1
OUTPUT=$HOST-$(date +"%Y-%m-%dT%H:%M:%S").tgz
BACKUP_DIR=$2/docker-backup/$HOST
MIN_BACKUP=2
MAX_SIZE=200000
MAX_FILE_COUNT=50
LOCAL=$(dirname "$(readlink -f "$0")")

rotate_backup() {
    mkdir -p "$BACKUP_DIR"
    if [ "$(ls -rt "$BACKUP_DIR"/*.tgz 2>/dev/null | wc -l)" -ge $MIN_BACKUP ]; then
        if [ "$(du -s "$BACKUP_DIR" | awk '{print $1}')" -ge $MAX_SIZE ] || [ "$(ls -rt "$BACKUP_DIR"/*.tgz 2>/dev/null | wc -l)" -ge $MAX_FILE_COUNT ]; then
            rm -v "$(find "$BACKUP_DIR"/*.tgz -type f | sort -z -n  | head -1)" && rotate_backup
        fi
    fi
}

rotate_backup
if ssh "$HOST" '[ -d /docker-data ]'; then
    if ssh "$HOST" '[ -d /docker-data/vaultwarden ]'; then
        ssh "$HOST" 'bash -s' <"$LOCAL/vaultwarden-db-backup"
    fi

    if ssh "$HOST" "cd / && tar cz docker-data" >"$BACKUP_DIR/$OUTPUT"; then
        echo "Backup $OUTPUT created"
        exit 0
    else
        echo "Backup from $HOST failed"
        exit 1
    fi
else
    echo "/docker-data not found on $HOST"
fi
